### Mini project: MNIST sample로 얕은 인공신경망을 만들어 봅시다.
- Input: (784 x 1)
- Weight: (10 x 784)
- Output: (10 x 1)
- $ Y = WX $

In [9]:
import pandas as pd
import numpy as np
from tensorflow.keras.datasets import mnist
import matplotlib.pyplot as plt

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
SCALE_FACTOR = 255
WIDTH = X_train.shape[1]
HEIGHT = X_train.shape[2]
X_train = X_train.reshape(X_train.shape[0],WIDTH*HEIGHT) / SCALE_FACTOR
X_test = X_test.reshape(X_test.shape[0],WIDTH*HEIGHT)  / SCALE_FACTOR

In [10]:
print(f"X_train.shape: {X_train.shape}, Y_train.shape: {Y_train.shape}")

X_train.shape: (60000, 784), Y_train.shape: (60000,)


In [12]:
input = X_train[0].reshape(WIDTH*HEIGHT, 1)
true = Y_train[0]
true = np.array([1 if i == true else 0 for i in range(10)]).reshape(10, 1)

In [13]:
weights = np.random.rand(10, WIDTH*HEIGHT) - 0.5
print(weights.shape)
print(input.shape)

(10, 784)
(784, 1)


In [14]:
alpha = 0.01
pred = np.dot(weights, input)
print(f"Prediction_previous: \n {pred}")

Prediction_previous: 
 [[-0.18134302]
 [ 4.88686471]
 [ 0.58477521]
 [ 0.04204074]
 [ 0.79287876]
 [ 3.45933491]
 [ 1.12938   ]
 [ 1.10600803]
 [-1.96534215]
 [ 0.57439234]]


In [7]:
error = (pred - true) ** 2
delta = pred - true
weight_deltas = np.outer(delta, input)

In [8]:
print(f"Prediction_previous: \n {pred.round(3)}")

for iter in range(100):
    error = (pred - true) ** 2
    delta = pred - true
    
    weight_deltas = np.outer(delta, input)
    weights -= alpha * weight_deltas

    # print(f"Weights: \n {weights}")
    # print(f"Weight_Deltas: {weight_delta}")

    pred = np.dot(weights, input)
    print(f"Iteration: {iter}, Prediction_current: \n {pred.round(3)}")

Prediction_previous: 
 [[-0.617]
 [-0.019]
 [-5.08 ]
 [-8.73 ]
 [-0.415]
 [-1.721]
 [-0.045]
 [ 2.314]
 [-0.081]
 [-0.141]]
Iteration: 0, Prediction_current: 
 [[-0.053]
 [-0.002]
 [-0.439]
 [-0.755]
 [-0.036]
 [ 0.765]
 [-0.004]
 [ 0.2  ]
 [-0.007]
 [-0.012]]
Iteration: 1, Prediction_current: 
 [[-0.005]
 [-0.   ]
 [-0.038]
 [-0.065]
 [-0.003]
 [ 0.98 ]
 [-0.   ]
 [ 0.017]
 [-0.001]
 [-0.001]]
Iteration: 2, Prediction_current: 
 [[-0.   ]
 [-0.   ]
 [-0.003]
 [-0.006]
 [-0.   ]
 [ 0.998]
 [-0.   ]
 [ 0.001]
 [-0.   ]
 [-0.   ]]
Iteration: 3, Prediction_current: 
 [[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [ 1.]
 [-0.]
 [ 0.]
 [-0.]
 [-0.]]
Iteration: 4, Prediction_current: 
 [[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [ 1.]
 [-0.]
 [ 0.]
 [-0.]
 [-0.]]
Iteration: 5, Prediction_current: 
 [[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [ 1.]
 [-0.]
 [ 0.]
 [-0.]
 [-0.]]
Iteration: 6, Prediction_current: 
 [[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [ 1.]
 [-0.]
 [ 0.]
 [-0.]
 [-0.]]
Iteration: 7, Prediction_current: 
 [

### Do as much samples as you want and observe prediction
### Consider how to evaluate predictions.

In [ ]:
def check_accuracy(weights, X, Y):
    correct = 0
    for samplenum in range(X.shape[0]):
        input = X[samplenum].reshape(WIDTH*HEIGHT, 1)
        pred = np.dot(weights, input)
        pred = np.argmax(pred)
        if pred == Y[samplenum]:
            correct += 1
    return correct / X.shape[0]

In [30]:
import pandas as pd
import numpy as np
from tensorflow.keras.datasets import mnist
import matplotlib.pyplot as plt

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
SCALE_FACTOR = 255
WIDTH = X_train.shape[1]
HEIGHT = X_train.shape[2]
X_train = X_train.reshape(X_train.shape[0],WIDTH*HEIGHT) / SCALE_FACTOR
X_test = X_test.reshape(X_test.shape[0],WIDTH*HEIGHT)  / SCALE_FACTOR

weights = np.random.rand(10, WIDTH*HEIGHT) - 0.5
alpha = 0.01
iteration = 1000000

for iter in range(iteration):
    ind = np.random.randint(X_train.shape[0])
    input = X_train[ind].reshape(WIDTH*HEIGHT, 1)
    true = Y_train[ind]
    true = np.array([1 if i == true else 0 for i in range(10)]).reshape(10, 1)
    
    pred = np.dot(weights, input)
    error = (pred - true) ** 2
    delta = pred - true

    weight_deltas = np.outer(delta, input)
    weights -= alpha * weight_deltas

    if iter % np.round(iteration/10) == 0:
        print(f"Iteration: {iter}, \
              Accuracy for train: {check_accuracy(weights, X_train, Y_train)}")

print(f"Accuracy for test: {check_accuracy(weights, X_test, Y_test)}")

Iteration: 0,               Accuracy for train: 0.10756666666666667
Iteration: 100000,               Accuracy for train: 0.6997666666666666
Iteration: 200000,               Accuracy for train: 0.6840666666666667
Iteration: 300000,               Accuracy for train: 0.6525166666666666
Iteration: 400000,               Accuracy for train: 0.7222833333333334
Iteration: 500000,               Accuracy for train: 0.71005
Iteration: 600000,               Accuracy for train: 0.7023166666666667
Iteration: 700000,               Accuracy for train: 0.6774
Iteration: 800000,               Accuracy for train: 0.7481166666666667
Iteration: 900000,               Accuracy for train: 0.7175833333333334
Accuracy for test: 0.7285
